# Test whether we can link to LLVM installed from apt.llvm.org or Homebrew.
---

name: Test

on: [push, pull_request]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Tools
        run: |
          curl -o llvm-18.1.6.src.tar.xz -L https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.6/llvm-18.1.6.src.tar.xz
          tar -xJF llvm-18.1.6.src.tar.xz
          ls
          mv llvm-18.1.6 llvm

